name: Get output from metadata
on: [issues, workflow_dispatch]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}" 